// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ToneoDeFutol.Api.Migrations
{
    [DbContext(typeof(ToneoDeFutolApiContext))]
    partial class ToneoDeFutolApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Torneo.Modelos.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Entrenador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Equipo");
                });

            modelBuilder.Entity("Torneo.Modelos.EventoPartido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipoID")
                        .HasColumnType("integer");

                    b.Property<int>("JugadorID")
                        .HasColumnType("integer");

                    b.Property<int>("Minuto")
                        .HasColumnType("integer");

                    b.Property<int>("PartidoID")
                        .HasColumnType("integer");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EquipoID");

                    b.HasIndex("JugadorID");

                    b.HasIndex("PartidoID");

                    b.ToTable("EventoPartido");
                });

            modelBuilder.Entity("Torneo.Modelos.InscripcionEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipoID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GrupoFaseGrupos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TorneoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EquipoID");

                    b.HasIndex("TorneoId");

                    b.ToTable("InscripcionEquipo");
                });

            modelBuilder.Entity("Torneo.Modelos.InscripcionJugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipoID")
                        .HasColumnType("integer");

                    b.Property<int>("JugadorID")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroCamiseta")
                        .HasColumnType("integer");

                    b.Property<int>("TorneoID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EquipoID");

                    b.HasIndex("JugadorID");

                    b.ToTable("InscripcionJugador");
                });

            modelBuilder.Entity("Torneo.Modelos.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Posicion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Jugador");
                });

            modelBuilder.Entity("Torneo.Modelos.Partido", b =>
                {
                    b.Property<int>("PartidoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PartidoID"));

                    b.Property<int>("EquipoLocalID")
                        .HasColumnType("integer");

                    b.Property<int>("EquipoVisitanteID")
                        .HasColumnType("integer");

                    b.Property<string>("EstadoPartido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GanadorPenalesID")
                        .HasColumnType("integer");

                    b.Property<int>("PuntosLocal")
                        .HasColumnType("integer");

                    b.Property<int>("PuntosVisitante")
                        .HasColumnType("integer");

                    b.Property<int?>("ResultadoLocal")
                        .HasColumnType("integer");

                    b.Property<int?>("ResultadoVisitante")
                        .HasColumnType("integer");

                    b.Property<int>("TorneoID")
                        .HasColumnType("integer");

                    b.Property<int>("VersionResultado")
                        .HasColumnType("integer");

                    b.HasKey("PartidoID");

                    b.HasIndex("EquipoLocalID");

                    b.HasIndex("EquipoVisitanteID");

                    b.HasIndex("GanadorPenalesID");

                    b.HasIndex("TorneoID");

                    b.ToTable("Partido");
                });

            modelBuilder.Entity("Torneo.Modelos.TorneoTipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoTorneo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Torneo");
                });

            modelBuilder.Entity("Torneo.Modelos.EventoPartido", b =>
                {
                    b.HasOne("Torneo.Modelos.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torneo.Modelos.Jugador", "Jugador")
                        .WithMany("EventosRegistrados")
                        .HasForeignKey("JugadorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torneo.Modelos.Partido", "Partido")
                        .WithMany()
                        .HasForeignKey("PartidoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Jugador");

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("Torneo.Modelos.InscripcionEquipo", b =>
                {
                    b.HasOne("Torneo.Modelos.Equipo", "Equipo")
                        .WithMany("InscripcionesTorneos")
                        .HasForeignKey("EquipoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torneo.Modelos.TorneoTipo", "Torneo")
                        .WithMany("InscripcionesEquipos")
                        .HasForeignKey("TorneoId");

                    b.Navigation("Equipo");

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("Torneo.Modelos.InscripcionJugador", b =>
                {
                    b.HasOne("Torneo.Modelos.Equipo", "Equipo")
                        .WithMany("InscripcionesJugadores")
                        .HasForeignKey("EquipoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torneo.Modelos.Jugador", "Jugador")
                        .WithMany("InscripcionesEquipos")
                        .HasForeignKey("JugadorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Jugador");
                });

            modelBuilder.Entity("Torneo.Modelos.Partido", b =>
                {
                    b.HasOne("Torneo.Modelos.Equipo", "EquipoLocal")
                        .WithMany()
                        .HasForeignKey("EquipoLocalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torneo.Modelos.Equipo", "EquipoVisitante")
                        .WithMany()
                        .HasForeignKey("EquipoVisitanteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torneo.Modelos.Equipo", "GanadorPenales")
                        .WithMany()
                        .HasForeignKey("GanadorPenalesID");

                    b.HasOne("Torneo.Modelos.TorneoTipo", "Torneo")
                        .WithMany("Partidos")
                        .HasForeignKey("TorneoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipoLocal");

                    b.Navigation("EquipoVisitante");

                    b.Navigation("GanadorPenales");

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("Torneo.Modelos.Equipo", b =>
                {
                    b.Navigation("InscripcionesJugadores");

                    b.Navigation("InscripcionesTorneos");
                });

            modelBuilder.Entity("Torneo.Modelos.Jugador", b =>
                {
                    b.Navigation("EventosRegistrados");

                    b.Navigation("InscripcionesEquipos");
                });

            modelBuilder.Entity("Torneo.Modelos.TorneoTipo", b =>
                {
                    b.Navigation("InscripcionesEquipos");

                    b.Navigation("Partidos");
                });
#pragma warning restore 612, 618
        }
    }
}
